Update Jest snapshots
cerner/terra-clinical pull request #842
Opened 2023-05-04 16:17 UTC by sdadn

### Summary

This PR updates snapshots for `terra-clinical-onset-picker` caused by a dependency update, so that snapshots are up to date and don't cause failures.

### Testing

This change was tested using:

- [ ] WDIO
- [x] Jest
- [ ] Visual testing (please attach a screenshot or recording)
- [ ] Other (please describe below)
- [ ] No tests are needed

### Reviews

In addition to engineering reviews, this PR needs:

- [ ] UX review
- [ ] Accessibility review
- [ ] Functional review

### Additional Details

---

Thank you for contributing to Terra.
@cerner/terra

2023-05-04 17:24 UTC, smason0 approved these changes

2023-05-04 19:17 UTC, supreethmr requested changes
is the role changing from combobox to button valid ..?? I am not able to find relevant changes on form-select and form-field component. Can you please share the relevant PR which has updated aria-attributes and role

2023-05-05 04:48 UTC, sdadn commented
> is the role changing from combobox to button valid ..?? I am not able to find relevant changes on form-select and form-field component. Can you please share the relevant PR which has updated aria-attributes and role

@supreethmr after searching, it seems like the combobox change was done in terra-form-select in https://github.com/cerner/terra-core/pull/3707. The snapshot changes in terra-clinical-onset-picker was triggered by the [v6.40.0 release](https://github.com/cerner/terra-core/pull/3788) of terra-form-select. 

Are the snapshot changes an intended side-effect? If not, then I propose we lock the terra-form-select dependency to `6.39.0` to fix the build failures for now and log a defect to fix this. Right now, the jest snapshot failures are blocking other PRs from merging.

2023-05-05 14:20 UTC, supreethmr approved these changes

2023-05-05 14:54 UTC, merged